name: Build Windows EXE

on:
  push:
    tags: [ "v*" ]       # dispara ao subir uma tag, ex.: v1.0.0
  workflow_dispatch:      # permite rodar manualmente na aba Actions

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build EXE
        run: >
          pyinstaller --noconfirm --onefile --windowed
          --name LEADSPRO
          --add-data "assets;assets"
          main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LEADSPRO
          path: dist/LEADSPRO.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/LEADSPRO.exe
